export const FETCH_POST_START = "FETCH_POST_START";
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
export const FETCH_POST_FAIL = "FETCH_POST_FAIL";

export const TOGGLE_ITEM_MODAL = "TOGGLE_ITEM_MODAL";
export const TOGGLE_LOGIN_MODAL = "TOGGLE_LOGIN_MODAL";
export const TOGGLE_REGISTER_MODAL = "TOGGLE_REGISTER_MODAL";
