export const FETCH_POST_START = "FETCH_POST_START";
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
export const FETCH_POST_FAIL = "FETCH_POST_FAIL";

export const TOGGLE_ITEM_MODAL = "TOGGLE_ITEM_MODAL";
export const TOGGLE_LOGIN_MODAL = "TOGGLE_LOGIN_MODAL";
export const TOGGLE_REGISTER_MODAL = "TOGGLE_REGISTER_MODAL";

export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const SET_ACCOUNT_START = "SET_ACCOUNT_START";

export const LOGOUT_START = "LOGOUT_START";