export const FETCH_POST_START = "FETCH_POST_START";
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
export const FETCH_POST_FAIL = "FETCH_POST_FAIL";

export const TOOGLE_ITEM_MODAL = "TOGGLE_ITEM_MODAL";